#include <Arduino.h>
String getWebPage(float *t, float *p, float *h, int *repVol, String state, String functionSelected) {
String page = "<!DOCTYPE html>";
page += "<html>";
page += "<head>";
page += "<meta charset='utf-8' />";
page += "    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=yes'>";
page += "    <meta name='description' content='IR Remote NAD L53'>";
page += "    <meta name='author' content='Jelco Huijser' >";
page += "<title>IR Remote NAD L53</title>";
page += "    <!-- Bootstrap core CSS -->";
page += "    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' rel='stylesheet'>";
page += "    <!-- Bootstrap theme -->";
page += "    <link href='https://getbootstrap.com/docs/3.3/dist/css/bootstrap-theme.min.css' rel='stylesheet'>";
page += "    <style media='screen' type='text/css'>";
page += "body {";
page += "  padding-top: 1rem;";
page += "  padding-bottom: 1rem;";
page += "}";
page += "h3 {";
page += "  margin-top: 1rem;";
page += "}";
page += ".row {";
page += "  margin-bottom: 1rem;";
page += "}";
page += ".row .row {";
page += "  margin-top: 1rem;";
page += "  margin-bottom: 0;";
page += "}";
page += "[class*='col-'] {";
page += "  padding-top: 1rem;";
page += "  padding-bottom: 1rem;";
page += "  background-color: rgba(86, 61, 124, .15);";
page += "  border: 1px solid rgba(86, 61, 124, .1);";
page += "}";
page += "hr {";
page += "  margin-top: 2rem;";
page += "  margin-bottom: 2rem;";
page += "}";
page += "table, td {";
page += "   border: 2px rgba(86, 61, 124, .15);";
page += "   text-align: center;";
page += "    padding: 3px;";
page += "}";
page += "</style>";
page += "</head>";
page += "<body>";
page += "      <div class='container'>";
page += "        <h3>Sensors</h3>";
page += "      <ul class='nav nav-pills' role='tablist'>";
page += "        <li role='presentation' class='active'><a href='#'>TE <span class='badge'>";
page +=           *t;
page += "</span></a></li>";
page += "        <li role='presentation' class='active'><a href='#'>LD <span class='badge'>";
page +=           *p;
page += "</span></a></li>";
page += "        <li role='presentation' class='active'><a href='#'>LV <span class='badge'>";
page +=           *h;
page += "</span></a></li>";
page += "      </ul>";
page += "        <form action='/' method='POST'> <button type='button submit' name='refresh' value='0' class='btn btn-sm btn-success'><span class='glyphicon glyphicon-refresh'></span></button>";
page += "       </form></div>";
page += "   <div class='container'>";
page += "         <h3>Remote</h3>";
page += "      <div class='row'>";
page += "        <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "        <button type='button submit' name='power' value='1' class='btn btn-sm btn-success'>Aan</button>";
page += "        <button type='button submit' name='power' value='0' class='btn btn-sm btn-danger'>Uit</button>";
page += "        <a href='#'>NAD L53 <span class='badge'>";
page +=           state;//Aan/Uit
page += "</span></a>";
page += "        </form>";
page += "        </div>";
page += "        <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "      <button type='button submit' name='function' value='0'  class='btn btn-sm btn-info'>CD/DVD</button>";
page += "         <button type='button submit' name='function' value='1'  class='btn btn-sm btn-info'>FM</button>";
page += "        <a href='#'>Selected <span class='badge'>";
page +=           functionSelected;//CD/DVD
page += "</span></a>";
page += "        </form>";
page += "        </div>";
page += "         <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "         <button type='button submit' name='dvd' value='0' class='btn btn-sm btn-success'><span class='glyphicon glyphicon-play'></span></button>";
page += "         <button type='button submit' name='dvd' value='1' class='btn btn-sm btn-warning'><span class='glyphicon glyphicon-pause'></span></button>";
page += "         <button type='button submit' name='dvd' value='3' class='btn btn-sm btn-danger'><span class='glyphicon glyphicon-stop'></span></button>";
page += "         <button type='button submit' name='dvd' value='2' class='btn btn-sm btn-primary'><span class='glyphicon glyphicon-eject'></span></button>";
page += "        </form></div>";
page += "         <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "<table>";
page += "<tr>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='volume' value='4'><span class='glyphicon glyphicon-volume-up'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-primary' name='volume' value='6'><span class='glyphicon glyphicon-plus'></span></button></td>";
page += "<td></td>";
page += "<td></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='cursor' value='up'>  <span class='glyphicon glyphicon-arrow-up'></span></button> </td>";
page += "<td></td>";
page += "<td></td>";
page += "</tr>";
page += "<tr>";
page += "<td><button type='button submit' class='btn btn-sm btn-danger' name='volume' value='0'><span class='glyphicon glyphicon-volume-off'> </span> </button></td>"; // mute
page += "<td> <a href='#'><span class='badge'>";
page +=           *repVol;//Aan/Uit
page += "</span></a></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-primary' name='cursor' value='skipbw'><span class='glyphicon glyphicon-backward'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='cursor' value='left'><span class='glyphicon glyphicon-arrow-left'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-success' name=cursor value='enter'><span class='glyphicon glyphicon-ok'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='cursor' value='right'><span class='glyphicon glyphicon-arrow-right'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-primary' name='cursor' value='skipfw'><span class='glyphicon glyphicon-forward'></span></button> </td>";
page += "</tr>";
page += "<tr>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='volume' value='3'><span class='glyphicon glyphicon-volume-down'></span></button></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-primary' name='volume' value='5'><span class='glyphicon glyphicon-minus'></span></button></td><td></td>";
page += "<td></td>";
page += "<td><button type='button submit' class='btn btn-sm btn-info' name='cursor' value='down'><span class='glyphicon glyphicon-arrow-down'></span></button> </td>";
page += "<td></td>";
page += "<td></td>";
page += "</tr>";
page += "</table>";
page += "    </form></div>";
page += "    <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='1'>1</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='2'>2</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='3'>3</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='4'>4</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='5'>5</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='6'>6</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='7'>7</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='8'>8</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='9'>9</button>";
page += "     <button type='button submit' class='btn btn-sm btn-default' name='cursor' value='0'>0</button>";
page += "    </form></div>";
page += "    <div class='col-6 col-sm-5'><form action='/' method='POST'>";
page += "     <button type='button submit' class='btn btn-sm btn-info'  name='function' value='2' >Sat/Cable</button>";
page += "     <button type='button submit' class='btn btn-sm btn-info'  name='function' value='3' >Video 4</button>";
page += "     <button type='button' class='btn btn-sm btn-primary'>TBD 1</button>";
page += "     <button type='button' class='btn btn-sm btn-primary'>TBD 2</button>";
page += "    </form></div>";
page += "        <div class='col-6 col-sm-5'>";
page += "        <button type='button' class='btn btn-sm btn-success'>Spotify</button>";
page += "         <button type='button' class='btn btn-sm btn-info'>Pong</button>";
page += "         </div>";
page += "         </div>";
page += "     </div>";
page += "   </div> <!-- /container -->";
page += "</body>";
page += "</html>";
return page;
}

